import { config } from "dotenv-mono";
import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";
import {
  accountTableRelations,
  activityTableRelations,
  apikeyTableRelations,
  assetTableRelations,
  columnTableRelations,
  commentTableRelations,
  externalLinkTableRelations,
  githubIntegrationTableRelations,
  integrationTableRelations,
  invitationTableRelations,
  labelTableRelations,
  notificationTableRelations,
  projectTableRelations,
  sessionTableRelations,
  taskRelationTableRelations,
  taskTableRelations,
  teamMemberTableRelations,
  teamTableRelations,
  timeEntryTableRelations,
  userNotificationPreferenceTableRelations,
  userNotificationWorkspaceProjectTableRelations,
  userNotificationWorkspaceRuleTableRelations,
  userTableRelations,
  verificationTableRelations,
  workflowRuleTableRelations,
  workspaceRoleTableRelations,
  workspaceTableRelations,
  workspaceUserTableRelations,
} from "./relations";
import { resolveDatabaseConnectionString } from "./resolve-database-url";
import {
  accountTable,
  activityTable,
  apikeyTable,
  assetActivityTable,
  assetAuditScanTable,
  assetAuditSessionTable,
  assetCostTable,
  assetCustodyTable,
  assetDisposalTable,
  assetFileTable,
  assetFuelLogTable,
  assetLocationTable,
  assetMaintenanceTable,
  assetMeterReadingTable,
  assetPmScheduleTable,
  assetReminderSentTable,
  assetRenewalTable,
  assetTable,
  assetTripTable,
  columnTable,
  commentTable,
  deviceCodeTable,
  driverProfileTable,
  externalLinkTable,
  githubIntegrationTable,
  gmApprovalChainTable,
  gmApprovalStepTable,
  gmAuditEventTable,
  gmCategoryTable,
  gmDepartmentTable,
  gmDistributionListTable,
  gmFilePlanNodeTable,
  gmNumberSchemeTable,
  gmNumberSequenceTable,
  gmOrganisationTable,
  gmRetentionClassTable,
  gmSecurityLabelTable,
  gmSenderProfileTable,
  gmSignatoryTable,
  gmSlaPolicyTable,
  gmTemplateTable,
  googleCalendarConnectionTable,
  integrationTable,
  invitationTable,
  labelTable,
  letterApprovalInstanceTable,
  letterApprovalStepInstanceTable,
  letterAssignmentTable,
  letterAttachmentTable,
  letterDispatchTable,
  letterDispositionTable,
  letterDraftVersionTable,
  letterLegalHoldTable,
  letterLinkTable,
  letterMinuteTable,
  letterMinuteUpdateTable,
  letterSignatureTable,
  letterTable,
  notificationTable,
  projectAccessRequestTable,
  projectMemberTable,
  projectTable,
  registeredAssetTable,
  sessionTable,
  taskAssignmentTable,
  taskCalendarEventTable,
  taskDriveAttachmentTable,
  taskMomTable,
  taskRelationTable,
  taskReminderSentTable,
  taskTable,
  teamMemberTable,
  teamTable,
  timeEntryTable,
  userNotificationPreferenceTable,
  userNotificationWorkspaceProjectTable,
  userNotificationWorkspaceRuleTable,
  userTable,
  verificationTable,
  workflowRuleTable,
  workOrderTable,
  workspacePageAccessTable,
  workspaceRoleTable,
  workspaceTable,
  workspaceUserTable,
} from "./schema";

config();

export const schema = {
  accountTable,
  activityTable,
  apikeyTable,
  assetActivityTable,
  assetAuditScanTable,
  assetAuditSessionTable,
  assetCostTable,
  assetCustodyTable,
  assetDisposalTable,
  assetFileTable,
  assetFuelLogTable,
  assetLocationTable,
  assetMaintenanceTable,
  assetMeterReadingTable,
  assetPmScheduleTable,
  assetReminderSentTable,
  assetRenewalTable,
  assetTable,
  assetTripTable,
  columnTable,
  commentTable,
  deviceCodeTable,
  driverProfileTable,
  externalLinkTable,
  githubIntegrationTable,
  gmApprovalChainTable,
  gmApprovalStepTable,
  gmAuditEventTable,
  gmCategoryTable,
  gmDepartmentTable,
  gmDistributionListTable,
  gmFilePlanNodeTable,
  gmNumberSchemeTable,
  gmNumberSequenceTable,
  gmOrganisationTable,
  gmRetentionClassTable,
  gmSecurityLabelTable,
  gmSenderProfileTable,
  gmSignatoryTable,
  gmSlaPolicyTable,
  gmTemplateTable,
  googleCalendarConnectionTable,
  integrationTable,
  invitationTable,
  labelTable,
  letterApprovalInstanceTable,
  letterApprovalStepInstanceTable,
  letterAssignmentTable,
  letterAttachmentTable,
  letterDispatchTable,
  letterDispositionTable,
  letterDraftVersionTable,
  letterLegalHoldTable,
  letterLinkTable,
  letterMinuteTable,
  letterMinuteUpdateTable,
  letterSignatureTable,
  letterTable,
  notificationTable,
  projectAccessRequestTable,
  projectMemberTable,
  projectTable,
  registeredAssetTable,
  sessionTable,
  taskAssignmentTable,
  taskCalendarEventTable,
  taskDriveAttachmentTable,
  taskMomTable,
  taskRelationTable,
  taskReminderSentTable,
  taskTable,
  teamMemberTable,
  teamTable,
  timeEntryTable,
  userNotificationPreferenceTable,
  userNotificationWorkspaceProjectTable,
  userNotificationWorkspaceRuleTable,
  userTable,
  verificationTable,
  workOrderTable,
  workflowRuleTable,
  workspacePageAccessTable,
  workspaceRoleTable,
  workspaceTable,
  workspaceUserTable,
  accountTableRelations,
  assetTableRelations,
  activityTableRelations,
  apikeyTableRelations,
  columnTableRelations,
  commentTableRelations,
  externalLinkTableRelations,
  githubIntegrationTableRelations,
  integrationTableRelations,
  invitationTableRelations,
  labelTableRelations,
  notificationTableRelations,
  projectTableRelations,
  sessionTableRelations,
  taskRelationTableRelations,
  taskTableRelations,
  teamMemberTableRelations,
  teamTableRelations,
  timeEntryTableRelations,
  userTableRelations,
  userNotificationPreferenceTableRelations,
  userNotificationWorkspaceProjectTableRelations,
  userNotificationWorkspaceRuleTableRelations,
  verificationTableRelations,
  workflowRuleTableRelations,
  workspaceRoleTableRelations,
  workspaceTableRelations,
  workspaceUserTableRelations,
};

type DatabaseInstance = ReturnType<typeof drizzle<typeof schema>>;

let pool: Pool | undefined;
let dbInstance: DatabaseInstance | undefined;

export function getDatabasePool(): Pool {
  if (!pool) {
    pool = new Pool({
      connectionString: resolveDatabaseConnectionString(),
    });
  }

  return pool;
}

export function getDatabase(): DatabaseInstance {
  if (!dbInstance) {
    dbInstance = drizzle(getDatabasePool(), {
      schema,
    });
  }

  return dbInstance;
}

const db = new Proxy({} as DatabaseInstance, {
  get(_target, property, receiver) {
    const value = Reflect.get(getDatabase(), property, receiver);

    if (typeof value === "function") {
      return value.bind(getDatabase());
    }

    return value;
  },
});

export default db;
